services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reload
      - ./src:/usr/src/app/src
      # Mount surveys for easy editing
      - ./src/surveys:/usr/src/app/surveys
      # Mount public files
      - ./src/public:/usr/src/app/public
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose for local database tools
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d surveydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
